### ISSUE TITLE
Pivy failes to build with Python 3.13

### ISSUE THREAD

**Issue by hobbes1069** [coin3d/pivy#107]
Looks like `PyEval_CallObject()` has been removed in Python 3.13:
https://docs.python.org/3.13/whatsnew/3.13.html#id10

Build output:
```
/builddir/build/BUILD/pivy-0.6.8/redhat-linux-build/pivy/gui/soqtPYTHON_wrap.cxx:4964:23: error: ‘PyEval_CallObject’ was not declared in this scope; did you mean ‘PyObject_CallObject’?
 4964 |           if (!(qev = PyEval_CallObject(shiboken_wrapinst_func, arglist))) {
      |                       ^~~~~~~~~~~~~~~~~
      |                       PyObject_CallObject
```

Fedora BZ link:
https://bugzilla.redhat.com/show_bug.cgi?id=2245811

**Comment by wwmayer** [comment]
> Looks like PyEval_CallObject() has been removed in Python 3.13:

It's already deprecated since Py3.9

**Comment by looooo** [comment]
should be fixed in master, can you test @hobbes1069 if python3.13 works now?

**Comment by looooo** [comment]
BTW.: there is a 0.6.9.a0 prerelease available.

**Comment by hobbes1069** [comment]
Confirmed.
